app:
  build: back
  ports:
    - 3005:3004
  links:
    - redis:redis
  environment:
    - redis_host=redis


redis:
  image: redis:3.0.5
  ports:
    - 6380:6379
  volumes:
    - ./redis-data:/data
    
front:
  build: front

nginx:
  build: nginx
  ports:
    - 8080:80
    - 443:443
  volumes_from:
    - front
  links:
    - app:app
    - front
