app:
  image: registry.sgmap.fr/api-particulier/back:latest
  container_name: apiparticulier-back
  ports:
    - 3005:3004
  volumes:
      - ./back/cert:/srv/apps/cert
      - ./tokens.json:/srv/apps/tokens.json

  environment:
    - log_format=bunyan


front:
  image: registry.sgmap.fr/api-particulier/front:latest

nginx:
  image: registry.sgmap.fr/api-particulier/nginx:latest
  container_name: apiparticulier-nginx
  ports:
    - 8088:80
  volumes_from:
    - front
  links:
    - app:app
    - front
